language: node_js
node_js:
- '0.10'
before_install:
- npm install coffee-script
before_script:
- ./node_modules/.bin/cake archive
script:
- ./node_modules/.bin/cake test
deploy:
  provider: releases
  api_key:
    secure: Fi9CTBS8m+MT59PX7cGo9I+9CXt/LJ4mo1U5hicexJIz5m53n653J0t4VYBWCCkQ5cMg2kgM+WftiFjUeB8kbFlrWWdcqB8KSMowg6fxO0TzHvYmtQmCduVYyUEmKxQQOM9ne/0qrBn3HJ2EixjafuHNlyEhKktPU/qlLb5IA5s=
  file: build/JavaApacheHttpClientFluentAPICodeGenerator.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: LuckyMarmot/Paw-JavaApacheHttpClientFluentAPICodeGenerator
